import {indexRooms,occupancy,filterRooms,occursOn,DAY_LABELS,nextFreeWindow,dailyClasses} from './model.js';
const $=id=>document.getElementById(id),labels={occupied:'Scheduled occupied',clear:'No scheduled class',unknown:'Unknown schedule'},termNames={'fall-2026':'2026 Fall','spring-2027':'2027 Spring'};
let data=null,titles={},rooms=[],selected=null,loadId=0,view='rooms',live=false;
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>n==null?'Unknown':`${(Math.floor(n/60)+11)%12+1}:${String(n%60).padStart(2,'0')} ${n<720?'AM':'PM'}`;
const days=value=>[...value].map(d=>DAY_LABELS[d]?.slice(0,3)||d).join(', ');
function now(){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).map(p=>[p.type,p.value]));$('date').value=`${parts.year}-${parts.month}-${parts.day}`;$('time').value=`${parts.hour}:${parts.minute}`;render();}
function message(text){$('message').textContent=text;$('message').hidden=!text;}
function validate(d){if(d.schema_version!==2||d.term!==termNames[$('term').value]||!d.courses||typeof d.courses!=='object'||Array.isArray(d.courses)||!Object.values(d.courses).every(c=>c&&Array.isArray(c.sections)))throw Error('The dataset does not match the selected term or scraper format.');}
async function load(){const id=++loadId;message('Updating course data…');$('reload').disabled=true;try{const r=await fetch(`../public/data/${$('term').value}.json`,{cache:'no-store'});if(!r.ok)throw Error('Could not load scraper data. Run start_classroom_finder.bat and retry.');const d=await r.json();if(id!==loadId)return;validate(d);data=d;message('');reindex();}catch(e){if(id===loadId){message(e.message);render();}}finally{if(id===loadId)$('reload').disabled=false;}}
function reindex(){rooms=indexRooms(data,titles).rooms;const previous=$('building').value;const buildings=[...new Set(rooms.map(r=>r.building))].sort();$('building').innerHTML='<option value="all">All buildings</option>'+buildings.map(b=>'<option value="'+escape(b)+'">'+escape(b)+'</option>').join('');$('building').value=buildings.includes(previous)?previous:'all';render();}
function render(){renderDay();const date=$('date').value,time=$('time').value,duration=+$('duration').value;
  if(!data){$('coverage').textContent='No dataset loaded.';$('rooms').innerHTML='<p class="empty">Course data will appear here. If loading fails, use Reload data.</p>';$('count').textContent='0';$('detail').innerHTML='<div class="welcome"><h2>Select a room</h2><p>Its class schedule will appear here.</p></div>';return;}
  const coverage=data.coverage||{},done=coverage.completed_courses??Object.values(data.courses).filter(c=>['ok','no_classes'].includes(c.status)&&!c.last_error).length,total=coverage.catalog_courses;
  $('coverage').textContent=`${data.term} · ${done}${total?` / ${total}`:''} courses scraped · ${rooms.length} rooms · ${data.updated_at?`Updated ${new Date(data.updated_at).toLocaleString('en-US',{timeZone:'America/Chicago'})} Central`:'No scrape yet'}. ${!total||done<total?'Partial coverage: rooms or bookings may be missing. ':''}Scheduled availability uses all loaded classes, regardless of course filters.`;
  if(!date||!time){$('rooms').innerHTML='<p class="empty">Choose a date and time.</p>';$('count').textContent='';$('detail').innerHTML='';return;}
  const visible=filterRooms(rooms,{query:$('query').value,roomQuery:$('roomQuery').value,state:$('state').value,building:$('building').value,campus:$('campus').value,date,time,duration});
  if(!visible.some(r=>r.id===selected))selected=visible[0]?.id??null;
  $('count').textContent=`${visible.length} found`;
  $('rooms').innerHTML=visible.map(r=>{const o=occupancy(r,date,time,duration),codes=[...new Set(r.meetings.map(m=>m.code))];return `<button class="room-card ${r.id===selected?'selected':''}" data-room="${escape(r.id)}" aria-pressed="${r.id===selected}"><div class="card-head"><strong>${escape(r.name)}</strong><span class="badge ${o.state}">${labels[o.state]}</span></div><p>${escape(codes.slice(0,5).join(' · '))}${codes.length>5?` · +${codes.length-5} more`:''}</p>${o.active.length?`<p>At this time: ${escape([...new Set(o.active.map(m=>m.code))].join(', '))}</p>`:''}</button>`;}).join('')||`<p class="empty">${rooms.length?'No rooms match these filters.':'Run scrape_fall_2026.bat to collect sections, then reload data. Online and unspecified locations do not appear as physical rooms.'}</p>`;
  const room=rooms.find(r=>r.id===selected);if(!room){$('detail').innerHTML='<div class="welcome"><h2>No room selected</h2><p>Try a different search or collect course data first.</p></div>';return;}
  const o=occupancy(room,date,time,duration),agenda=room.meetings.filter(m=>occursOn(m,date)).sort((a,b)=>a.start-b.start),all=[...room.meetings].sort((a,b)=>a.code.localeCompare(b.code)||((a.start??0)-(b.start??0)));
  $('detail').innerHTML=`<div class="detail-heading"><h2>${escape(room.name)}</h2><span class="badge ${o.state}">${labels[o.state]}</span></div><p class="subtle">${room.meetings.length} distinct meeting patterns. This schedule shows every loaded class in this room.</p><p class="subtle">Checking ${duration?duration+' minutes starting at '+escape(time):'the selected instant'}. ${duration&&o.state!=='unknown'&&nextFreeWindow(room,date,time,duration)!==null?'Next '+duration+' minute window without a recorded class: '+fmt(nextFreeWindow(room,date,time,duration))+'.':''} This does not guarantee access or reservation availability.</p><div class="room-timeline" aria-label="Full-day room timeline"><span>12 AM</span><div class="timeline-track">${agenda.map(m=>`<span class="timeline-block ${o.active.includes(m)?'active':''}" style="left:${100*m.start/1440}%;width:${100*(m.end-m.start)/1440}%" title="${escape(m.code)} · ${fmt(m.start)}–${fmt(m.end)}"></span>`).join('')}</div><span>12 AM</span></div><h3 class="section-title">Daily schedule · ${escape(date)}</h3><div class="agenda">${agenda.map(m=>`<article class="meeting ${o.active.includes(m)?'active':''}"><time>${fmt(m.start)}<br>– ${fmt(m.end)}</time><div><strong>${escape(m.code)} · ${escape(m.title)}</strong><p>Section ${escape(m.section)} · Class ${escape(m.classNumber)}</p><p>${escape(m.instructor)}</p></div></article>`).join('')||'<p class="subtle">No dated classes scheduled in the loaded data for this day.</p>'}</div>${room.meetings.some(m=>!m.known)?'<p class="subtle">Some meetings have unknown times, days, or date ranges. Check the full schedule below.</p>':''}<h3 class="section-title">Full term schedule</h3><div class="table-wrap"><table class="all-meetings"><thead><tr><th>COURSE / SECTION</th><th>DAYS / TIME</th><th>DATES</th></tr></thead><tbody>${all.map(m=>`<tr><td><strong>${escape(m.code)}</strong><br>${escape(m.title)}<br><span class="day-label">Section ${escape(m.section)} · ${escape(m.classNumber)}</span></td><td>${escape(days(m.days)||'Unknown days')}<br>${m.start!==null&&m.end!==null?`${fmt(m.start)} – ${fmt(m.end)}`:escape(m.rawTime)}</td><td>${escape(m.dates||'Unknown dates')}</td></tr>`).join('')}</tbody></table></div>`;
}
$('rooms').addEventListener('click',e=>{const b=e.target.closest('[data-room]');if(b){selected=b.dataset.room;render();if(window.matchMedia('(max-width:700px)').matches){$('detail').scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});$('detail').focus({preventScroll:true});}}});
for(const id of ['query','roomQuery','date','time','state','building','campus','duration'])$(id).addEventListener('input',render);
$('now').addEventListener('click',now);$('reload').addEventListener('click',load);$('term').addEventListener('change',load);
fetch('../public/data/catalog-index.json').then(r=>r.ok?r.json():{}).then(t=>{titles=t;if(data)reindex();}).catch(()=>{});
now();load();

const modes=['light','dark','system'],media=window.matchMedia('(prefers-color-scheme: dark)');let theme='system';try{const saved=JSON.parse(localStorage.getItem('unt-theme-v3'));if(modes.includes(saved))theme=saved;}catch{}
function applyTheme(){document.documentElement.dataset.theme=theme==='system'?(media.matches?'dark':'light'):theme;const next=modes[(modes.indexOf(theme)+1)%3];$('theme').textContent={light:'☀',dark:'☾',system:'◧'}[theme];$('theme').setAttribute('aria-label',`Theme: ${theme}. Switch to ${next}`);$('theme').title=`Theme: ${theme}`;}
$('theme').addEventListener('click',()=>{theme=modes[(modes.indexOf(theme)+1)%3];try{localStorage.setItem('unt-theme-v3',JSON.stringify(theme));}catch{}applyTheme();});media.addEventListener('change',applyTheme);applyTheme();

function setView(next){view=next;document.body.dataset.view=next;$('roomWorkspace').hidden=view!=='rooms';$('today').hidden=view!=='today';$('viewRooms').setAttribute('aria-pressed',view==='rooms');$('viewToday').setAttribute('aria-pressed',view==='today');render();}
function renderDay(){const list=dailyClasses(rooms,{date:$('date').value,time:$('time').value,query:$('query').value,roomQuery:$('roomQuery').value,building:$('building').value,campus:$('campus').value,state:$('dayState').value,group:$('dayGroup').value});$('liveInfo').textContent=`${live?'Live · following current Central time':'Browsing '+$('date').value+' · '+$('time').value+' Central'} · ${list.length} scheduled meetings. Live mode follows the timetable, not room sensors.`;let last='';$('dayClasses').innerHTML=list.map(m=>{const group=$('dayGroup').value==='building'?m.building:$('dayGroup').value==='course'?m.code:fmt(m.start);const heading=group!==last?`<h3 class="day-group">${escape(group)}</h3>`:'';last=group;return heading+`<button class="day-class ${m.phase}" data-day-room="${escape(m.roomId)}"><time>${fmt(m.start)}–${fmt(m.end)}</time><span><b>${escape(m.code)} · ${escape(m.title)}</b><small>${escape(m.room)} · Section ${escape(m.section)} · ${escape(m.instructor)}</small></span><span class="badge ${m.phase==='active'?'occupied':'clear'}">${m.phase==='active'?'Happening now':m.phase==='upcoming'?'Upcoming':'Finished'}</span></button>`;}).join('')||'<p class="empty">No dated meetings match. Try All day or different filters. Unknown schedules and uncollected courses may be missing.</p>';}
function stopLive(){live=false;$('live').setAttribute('aria-pressed','false');$('live').textContent='● Live mode';}
$('live').addEventListener('click',()=>{if(live){stopLive();render();return;}live=true;$('live').setAttribute('aria-pressed','true');$('live').textContent='● Live on';$('dayState').value='active';now();setView('today');});
$('viewRooms').addEventListener('click',()=>setView('rooms'));$('viewToday').addEventListener('click',()=>setView('today'));
for(const id of ['dayGroup','dayState'])$(id).addEventListener('input',render);
for(const id of ['date','time'])$(id).addEventListener('input',()=>{stopLive();render();});
$('dayClasses').addEventListener('click',e=>{const row=e.target.closest('[data-day-room]');if(!row)return;selected=row.dataset.dayRoom;$('state').value='all';setView('rooms');$('detail').scrollIntoView({block:'start',behavior:'smooth'});$('detail').focus({preventScroll:true});});
setInterval(()=>{if(live&&!document.hidden)now();},30000);document.addEventListener('visibilitychange',()=>{if(live&&!document.hidden)now();});

setInterval(()=>{if(live&&!document.hidden&&!$('reload').disabled)load();},300000);
